export const FETCH_FLEET        = 'FETCH_FLEET';
export const FETCH_FLEET_SUCCESS= 'FETCH_FLEET_SUCCESS';
export const FETCH_FLEET_FAILURE= 'FETCH_FLEET_FAILURE';

export const SAVE_NEW_FLEET             = 'SAVE_NEW_FLEET';
export const SAVE_NEW_FLEET_SUCCESS     = 'SAVE_NEW_FLEET_SUCCESS';
export const SAVE_NEW_FLEET_FAILURE     = 'SAVE_NEW_FLEET_FAILURE';