export const FETCH_USERPROFILE          = 'FETCH_USERPROFILE';
export const FETCH_USERPROFILE_SUCCESS  = 'FETCH_USERPROFILE_SUCCESS';
export const FETCH_USERPROFILEFAILED    = 'FETCH_USERPROFILEFAILED';